/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kreative_acc_pushchar_MacCharInFont */

#ifndef _Included_com_kreative_acc_pushchar_MacCharInFont
#define _Included_com_kreative_acc_pushchar_MacCharInFont
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kreative_acc_pushchar_MacCharInFont
 * Method:    inFont
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_kreative_acc_pushchar_MacCharInFont_inFont__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_kreative_acc_pushchar_MacCharInFont
 * Method:    inFont
 * Signature: (Ljava/lang/String;II)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_kreative_acc_pushchar_MacCharInFont_inFont__Ljava_lang_String_2II
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_kreative_acc_pushchar_MacCharInFont
 * Method:    inFont
 * Signature: (Ljava/lang/String;[I)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_kreative_acc_pushchar_MacCharInFont_inFont__Ljava_lang_String_2_3I
  (JNIEnv *, jclass, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
